./vtt.sh "AI Angels, Demons, and the Fight for the Future (w⧸ Philip Rosedale) [m_bF46IjNCI].en.vtt"
./vtt.sh "Ari Kuschnir： Trump Ayahuasca - AI and the Alchemical Imaginary ｜ Team Human w⧸ Rushkoff #347 [EFooQkVmGt4].en.vtt"
./vtt.sh "Do Tech Billionaires Want Us Dead？ (w⧸ @TaylorLorenz) [yWEMGi0ll10].en.vtt"
./vtt.sh "Don’t Shoot the Messenger： AI is not the problem ｜ Team Human Podcast w⧸ Douglas Rushkoff ep. 326 [TAAw64hSQX4].en.vtt"
./vtt.sh "Enshittification – And How We Stop It (w⧸Cory Doctorow) [e2NkmPI88k4].en.vtt"
./vtt.sh "Peter Thiel Called This the Work of the Antichrist (w⧸ Tom Llewellyn) [ElX0HMuBGqg].en.vtt"
./vtt.sh "Program Or Be Programmed Book Launch ｜ Q&A w⧸ Douglas Rushkoff & Matt Klein [Y6NiQLpMjIY].en.vtt"
./vtt.sh "STYX - THEY DIDN'T WANT YOU TO KNOW - Behind the Scenes Exposed [XIO2IY4Q7bg].en.vtt"
./vtt.sh "The AI Deepfake Porn Economy Nobody's Talking About (w⧸ Kat Tenbarge) [x8JYQ2d4ofs].en.vtt"
./vtt.sh "The End of Employment (And Why It Could Free Us) [0Q62CxA4ikw].en.vtt"
./vtt.sh "The Enemies of Humanity Are Wielding Occult Power (w⧸ Grant Morrison) [nPzqCI_jwOQ].en.vtt"
./vtt.sh "The Holy War Delusion： Is it Time to Retire Our Religions？ [QxlFOVt6eJw].en.vtt"
./vtt.sh "The Internet Felt Like This in 1994. AI Might Be Our Last Chance. [V8Rd-PVG2pU].en.vtt"
./vtt.sh "The Internet Is an Occult Machine (w⧸ Shira Chess) [WWOpClSlicE].en.vtt"
./vtt.sh "＂What If＂ Is the Enemy of Fascism (w⧸Brian Eno) [vV0CM8smqU8].en.vtt"
